repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.9.0
    hooks:
    - id: pyupgrade
      args: ["--py10-plus"]
default_language_version:
    python: python3.10

